### ISSUE TITLE
Review Dane codes in colombia municipalities and departments

### ISSUE THREAD

**Issue by CamilaAchuri** [datasketch/geodata#28]
El "id" en centroides no esta tomando el cero inicial de algunos codigos que lo llevan, como
por ejemplo Antioquia, cuyo codigo es 05 aparece como 5, pasa tanto en municipios como en
departamentos

**Comment by jpmarindiaz** [comment]
Tenemos que hacer que funcione de las dos formas para los datos de entrada, cuando los meten con 0 y sin 0
